### ISSUE TITLE
[Bug]: Speak while dead

### ISSUE THREAD

**Issue by Tennessin** [ARMA-FiveM/issue-tracker#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

You can speak while dead (Finished off)

### Expected behaviour

Being able to speak while dead?

### Steps to reproduce

1. Die
2. Use Voicechat

### Any Texture Packs? (If so list)

Not relevant

### ARMA User ID

Not relevant

**Comment by kwt** [comment]
This works as intended currently, in future it may be added to increase roleplay however at the moment it'll stay how it is. If people talk whilst dead and you have an issue with it, you can report them for fail rp.
