### ISSUE TITLE
[Bug]: RP Zones

### ISSUE THREAD

**Issue by randomahhhname** [ARMA-FiveM/issue-tracker#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While in a RP Zone you can not pull out weapons, but when someones out of one they can shoot you while your in the zone. Unfair disadvantage.

### Expected behaviour

x

### Steps to reproduce

x

### Any Texture Packs? (If so list)

x

### ARMA User ID

9

**Comment by kwt** [comment]
Works as intended, RP zones have the option to enable weapon classes and disable damage. 
![image](https://user-images.githubusercontent.com/122835363/213944846-271cbc55-8907-4a93-a88c-c9ef1f3a014f.png)
![image](https://user-images.githubusercontent.com/122835363/213944850-ddfa3e0e-87b6-4df2-a58b-a3cf60ae88bd.png)
