### ISSUE TITLE
[Bug]: casino bug

### ISSUE THREAD

**Issue by Trk1905** [ARMA-FiveM/issue-tracker#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i put the chips in. He got 2 cards and he gave me zero and then the game just ended.

### Expected behaviour

ok

### Steps to reproduce

https://streamable.com/pemiby

### Any Texture Packs? (If so list)

15mil

### ARMA User ID

999

**Comment by kwt** [comment]
Please make a comp request in the discord.
