### ISSUE TITLE
[Bug]: A car lock runs out of fuel extremely quickly and Its very annoying

### ISSUE THREAD

**Issue by oliidev** [ARMA-FiveM/issue-tracker#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you drive a lock imported through the use of real currency through the Arma store, the fuel runs out very quickly

### Expected behaviour

N/A

### Steps to reproduce

L

### Any Texture Packs? (If so list)

Nope

### ARMA User ID

121

**Comment by kwt** [comment]
Is this still an issue? I believe it was resolved recently as the fuel variable did not match the data type of the table.

**Comment by kwt** [comment]
No response, and I've failed to see it occur recently, believe it was just a data type issue.
