### ISSUE TITLE
[BUG] Rust hit marker sounds not working

### ISSUE THREAD

**Issue by Donkkkkk** [ARMA-FiveM/issue-tracker#13]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have enabled hit sounds from F2 but they are still not working.

### Expected behaviour

hit sounds to work when you shoot someone

### Steps to reproduce

1. f2
2. turn on hitsounds
3. they should work

### Any Texture Packs? (If so list)

no

### ARMA User ID

566

**Comment by kwt** [comment]
Have you got cod hitmarkers enabled? If so disable those and you should have the default rust sounds for headshots and body shots as long as you have experimental hitmarker sounds enabled.

**Comment by kwt** [comment]
No response, a quick rundown on the hitsounds
- You enable them in F2 (settings), they're stored in kvp whether they are enabled/disabled
- Having the COD hitmarker sounds enabled overwrites this, once your subscription ends this should revert back to the initial hitmarker sounds.
