### ISSUE TITLE
[Bug]: car bug

### ISSUE THREAD

**Issue by brikcs** [ARMA-FiveM/issue-tracker#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://streamable.com/txwyci

### Expected behaviour

https://streamable.com/txwyci

### Steps to reproduce

https://streamable.com/txwyci

### Any Texture Packs? (If so list)

https://streamable.com/txwyci

### ARMA User ID

91

**Comment by kwt** [comment]
This was due to a weapon being removed, should no longer cause an issue.
