### ISSUE TITLE
[Bug]: move all thing

### ISSUE THREAD

**Issue by 2801M** [ARMA-FiveM/issue-tracker#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when pressing move all, if it cant fit all of the items it will not move any rather than moving the max amount

### Expected behaviour

awdd

### Steps to reproduce

wad

### Any Texture Packs? (If so list)

awda

### ARMA User ID

4

**Comment by S1i** [comment]
Reproduceable 👍

**Comment by kwt** [comment]
This is in suggestions, will be added soon once I've finished dono tickets.
