### ISSUE TITLE
[Bug]: Wardrobes Not Working

### ISSUE THREAD

**Issue by oliidev** [ARMA-FiveM/issue-tracker#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you open the wardrobe subcategory at a clothing changer, the menu disappears. I have plat so that is not the issue.

### Expected behaviour

I am unable to put on a saved outfit and this very annoying as i dont know my outfit numbers.

### Steps to reproduce

1. Open Clothing Changer
2. Press the wardrobe sub category
3. It opens up a menu listing your saved outfits etc. (This is the part that is broken)

### Any Texture Packs? (If so list)

Nope

### ARMA User ID

121

**Comment by kwt** [comment]
Failed to replicate, make sure you have platinum subscription if this is in a clothing store.
