### ISSUE TITLE
[Bug]: “Move All” Not working 

### ISSUE THREAD

**Issue by BraveWaffle** [ARMA-FiveM/issue-tracker#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Move all Button got diamond process does not move uncut diamonds to inventory with the "Move All" button , this should move the max amount of Ifems to the players inventory

### Expected behaviour

To Move all items that the plates inventory can hold at the time 

### Steps to reproduce

Opens Boot of Car 
clicks move all from van to players inventory 
“Not enough space in players inventory “
(The move all button should move as much of the item as possible depending on players inventory space, when not carrying anything it still does not move items ) 

### Any Texture Packs? (If so list)

N/A

### ARMA User ID

262

**Comment by S1i** [comment]
This has already been reported [here](https://github.com/ARMA-FiveM/issue-tracker/issues/16).

**Comment by kwt** [comment]
This should be sorted for restart.
