### ISSUE TITLE
[Bug]: Missing Advanced Rebel Weapons.

### ISSUE THREAD

**Issue by Tennessin** [ARMA-FiveM/issue-tracker#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

MXM
MK-1 EMR
Spar 17
etc needs to be added

### Expected behaviour

Not relevant

### Steps to reproduce

Not relevant

### Any Texture Packs? (If so list)

Not relevant

### ARMA User ID

Not relevant

**Comment by kwt** [comment]
Pending weapons update

**Comment by kwt** [comment]
These weapons should now be available to purchase in the Rebel gunstore, provided you have the Advanced Rebel license.
