### ISSUE TITLE
[Bug]: Large arms turf

### ISSUE THREAD

**Issue by Samorooni** [ARMA-FiveM/issue-tracker#21]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Every time me and my gang go to capture large we get there and press E at the red thing and nothing happens, yesterday it said that we already owned it even though BBCC.

Also only me the gang leader can take turfs.

### Expected behaviour

Should be able to take it.

### Steps to reproduce

Go to large arms
Press E on capture location
Nothing happens.

### Any Texture Packs? (If so list)

Nah

### ARMA User ID

272

**Comment by kwt** [comment]
This should be resolved for next restart.
