### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 2801M** [ARMA-FiveM/issue-tracker#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://user-images.githubusercontent.com/123016161/213269937-133025f7-7e92-41d6-8a24-929d7a9e1162.png)
FIX THE CIRCLE, it stays there for ages when it isnt necessary 

### Expected behaviour

awdadwadaw

### Steps to reproduce

a

### Any Texture Packs? (If so list)

no

### ARMA User ID

4

**Comment by kwt** [comment]
Fixed for restart
