### ISSUE TITLE
[Bug]: NHS NHS NHS NHS REVIVEY WIVEY

### ISSUE THREAD

**Issue by brikcs** [ARMA-FiveM/issue-tracker#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

you can go to any alive player and revive them for 5k

### Expected behaviour

you can go to any alive player and revive them for 5k

### Steps to reproduce

you can go to any alive player and revive them for 5kyou can go to any alive player and revive them for 5k

### Any Texture Packs? (If so list)

you can go to any alive player and revive them for 5kyou can go to any alive player and revive them for 5kyou can go to any alive player and revive them for 5kyou can go to any alive player and revive them for 5k

### ARMA User ID

1563123

**Comment by kwt** [comment]
Fixed for restart.
