### ISSUE TITLE
[Bug]: Drops Not working

### ISSUE THREAD

**Issue by Tennessin** [ARMA-FiveM/issue-tracker#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Drops are very bugged and multiple spawn in at the same time, you can also not loot it.

### Expected behaviour

Not relevant

### Steps to reproduce

Not relevant

### Any Texture Packs? (If so list)

Not relevant

### ARMA User ID

Not relevant

**Comment by S1i** [comment]
I believe the developers have known of this and are working on it currently.

**Comment by kwt** [comment]
I believe this issue is resolved, as far as the actual airdrops go.
