### ISSUE TITLE
can knock out in organ[Bug]: 

### ISSUE THREAD

**Issue by 2801M** [ARMA-FiveM/issue-tracker#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

can knock out in organ

### Expected behaviour

aadad

### Steps to reproduce

awdawda

### Any Texture Packs? (If so list)

awdad

### ARMA User ID

4

**Comment by kwt** [comment]
Knockout has been disabled in Organ Heist from next restart. 12 AM.
