### ISSUE TITLE
[Bug]: Ban Message

### ISSUE THREAD

**Issue by randomahhhname** [ARMA-FiveM/issue-tracker#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

remove banning admin from ban message, leads to doxxing.

### Expected behaviour

xx

### Steps to reproduce

xx

### Any Texture Packs? (If so list)

xx

### ARMA User ID

9

**Comment by ghillieee** [comment]
not really a bug, should've been a suggestion

**Comment by kwt** [comment]
You've posted this 15 minutes after an update was pushed to remove it.
